name: Run `prettier` on a branch
on:
  workflow_dispatch:
jobs:
  prettier:
    if: ${{ github.repository == 'grafana/writers-toolkit' }}
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/writers-toolkit/prettier@b37a5a3fdb432c12d5f8fd8021e53b057a829a7c # prettier/v2.0.1
        with:
          branch: ${{ env.GITHUB_REF }}
